spring.application.name=authservice
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/heartme_db_patched
spring.jpa.properties.hibernate.default_schema=auth
spring.datasource.username=admin
spring.datasource.password=admin

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Actuator/Health
# management.endpoints.web.exposure.include=health,info

# JWT
jwt.secret=minhaChaveSuperSecretaComMaisDe32Bytes123!
jwt.expirationMinutes=60
