spring.application.name=notificationservice
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/heartme_db_patched
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=notifications

jwt.secret=${JWT_SECRET:minhaChaveSuperSecretaComMaisDe32Bytes123!}
