spring.application.name=userservice
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/heartme_db_patched
spring.jpa.properties.hibernate.default_schema=users
spring.datasource.username=admin
spring.datasource.password=admin

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=minhaChaveSuperSecretaComMaisDe32Bytes123!
jwt.expirationMinutes=60

auth.service.base-url=${AUTH_SERVICE_BASE_URL:http://localhost:8080}
post.service.base-url=${POST_SERVICE_BASE_URL:http://localhost:8082}
notification.service.base-url=${NOTIFICATION_SERVICE_BASE_URL:http://localhost:8083}
